Repository kw-bookmedicine/frontend, pull requests merged in 2024-05, with the labels that each got.

#163 💄 Style: 마이페이지 UI 수정 및 서비스 추가
  public/icon/profile/basic_profile_img.svg
  public/icon/profile/profile_prscr_icon.svg
  public/icon/profile/profile_worry_icon.svg
  public/images/profile_bg.png
  src/components/Button.jsx
  src/components/Modal/MyListModal.jsx
  src/components/PickBookItem.jsx
  src/pages/Edit.jsx
  src/pages/Mypage.jsx
  src/pages/UserInfo.jsx
  src/styles/Button.module.css
  src/styles/Edit.css
  src/styles/Footer.module.css
  src/styles/MyPage.css
  src/styles/UserInfo.css
Labels: :art: Design, :memo: Docs, :lipstick: Style, :recycle: Refactor, ➕Add

#164 📝 Docs: 중분류, 책 상세정보 보기 페이지 수정
  src/components/BookListSlide.jsx
  src/components/Header.js
  src/pages/BookDetail.jsx
  src/pages/BookList.jsx
  src/pages/SmallCategory.jsx
  src/styles/ArrowTitle.module.css
  src/styles/BookCard.module.css
  src/styles/BookDetail.css
  src/styles/BookDetailCard.css
  src/styles/BookList.css
  src/styles/Footer.module.css
  src/styles/HashTag.css
  src/styles/SmallCategory.css
Labels: :bug: bug, :art: Design, :memo: Docs, :lipstick: Style, :recycle: Refactor

#166 ✨ Feat: 회원가입 과정 기능 추가
  public/icon/join/left_arrow.png
  public/icon/join/right_arrow.png
  src/components/HashTag.js
  src/components/checkBox.jsx
  src/components/interestGrid.jsx
  src/pages/Login/Signup1.jsx
  src/pages/Login/Signup3.jsx
  src/styles/HashTag.css
  src/styles/JoinStyles.css
  src/styles/Signup3.css
Labels: :art: Design, :sparkles: Feat, :memo: Docs, ➕Add

#170 🎨 Design: 로그인 전 홈 화면 기능 소개 UI 추가
  public/icon/home/home_prscrCard_icon-group.svg
  public/icon/home/home_prscrCard_icon.svg
  public/temp-robot-icon.png
  src/pages/Home.jsx
  src/styles/HomeStyles.css
Labels: :art: Design, ➕Add

#171 🐛 Fix: 책 데이터 가져올 때 생기는 에러 수정
  src/pages/BookDetail.jsx
  src/pages/Search/Search.jsx
Labels: :bug: bug

#173 📝 Docs: 직업선택 value값 수정
  src/pages/Login/Signup2.jsx
Labels: :memo: Docs

#174 Delete: 필요없는 이미지 삭제
  src/assets/1.png
  src/assets/icons8-별-30 (1).png
  src/assets/icons8-빈별-30 (2).png
  src/assets/icons8-스타-반-빈-30.png
Labels: :recycle: Refactor

#176 ✨ Feat: 고민 상담 페이지 API 연결
  public/icon/prscr-category/Children_Parenting-icon.svg
  public/icon/prscr-category/Economy_Management-icon.svg
  public/icon/prscr-category/Employment_Career-icon.svg
  public/icon/prscr-category/Etc-icon.svg
  public/icon/prscr-category/Fiction_Essays-icon.svg
  public/icon/prscr-category/Health-icon.svg
  public/icon/prscr-category/History-icon.svg
  public/icon/prscr-category/Hobbies-icon.svg
  public/icon/prscr-category/Philosophy-icon.svg
  public/icon/prscr-category/Relationships_Communication-icon.svg
  public/icon/prscr-category/Science_Math_Engineering-icon.svg
  public/icon/prscr-category/Society-icon.svg
  public/icon/prscr-category/Workbook_Examination-icon.svg
  src/App.js
  src/components/Prescription/CounselingView.jsx
  src/pages/Prescription/Counseling.jsx
Labels: :sparkles: Feat, ➕Add

#177 :art: Design: 책 검색 페이지, 화면 비율 축소 및 카테고리 패딩 수정
  src/styles/SearchStyles.css
Labels: :art: Design

#181 ✨ Feat: 페이지네이션 책 데이터 요청 사이즈만큼 처리
  src/components/Pagination.jsx
  src/components/Search/SearchBox.jsx
  src/components/SearchBox.jsx
  src/hooks/useInput.js
  src/hooks/useLogin.js
  src/hooks/useLoginForm.js
  src/pages/Login/Login.jsx
  src/pages/Login/PasswordFind.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/styles/SearchResultList.css
Labels: :sparkles: Feat

#188 ✨ Feat: worry-detail 페이지 api.prescription 게시물에 대한 처방전 조회 api 연결
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/Worry/WorryDetail.jsx
  src/styles/Prescription/WidePrescriptionCard.css
  src/util/index.js
  src/util/toYYYYMMDD.js
Labels: :sparkles: Feat

#190 ✨ Feat: 한 줄 처방 작성 페이지 기능 구현
  package.json
  src/App.css
  src/App.js
  src/components/Modal/SearchBook.jsx
  src/components/Prescription/ProcessTitle.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/styles/Button.module.css
  src/styles/Counseling/ProcessTitle.css
  src/styles/Prescription/OneLinePrescription.css
  src/styles/SearchBookModal.css
Labels: :art: Design, :sparkles: Feat, :memo: Docs, :lipstick: Style

#196 🎨 Design: 한 줄 처방 목록 페이지 바뀐 UI로 적용
  public/icon/oneLine-prscr/laughing.png
  public/icon/oneLine-prscr/like.png
  src/components/HashTag.js
  src/components/Prescription/OneLinePrscrCard.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/styles/HashTag.css
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Prescription/OneLinePrscrCard.css
Labels: :art: Design

#197 ♻️ Refactor: 고민 키워드 코드 리팩토링
  public/icon/prscr-category/건강-icon.svg
  public/icon/prscr-category/경제_경영-icon.svg
  public/icon/prscr-category/관계_소통-icon.svg
  public/icon/prscr-category/기타-icon.svg
  public/icon/prscr-category/문제집_수험서-icon.svg
  public/icon/prscr-category/사회-icon.svg
  public/icon/prscr-category/소셜_에세이-icon.svg
  public/icon/prscr-category/수학_과학_공학-icon.svg
  public/icon/prscr-category/역사-icon.svg
  public/icon/prscr-category/자녀_양육-icon.svg
  public/icon/prscr-category/철학-icon.svg
  public/icon/prscr-category/취미-icon.svg
  public/icon/prscr-category/취업-icon.svg
  src/pages/Prescription/Counseling.jsx
Labels: :recycle: Refactor

#198 🚀 Deploy: 지도교수님 미팅 전 배포
  package.json
  public/icon/oneLine-prscr/laughing.png
  public/icon/oneLine-prscr/like.png
  public/icon/prscr-category/건강-icon.svg
  public/icon/prscr-category/경제_경영-icon.svg
  public/icon/prscr-category/관계_소통-icon.svg
  public/icon/prscr-category/기타-icon.svg
  public/icon/prscr-category/문제집_수험서-icon.svg
  public/icon/prscr-category/사회-icon.svg
  public/icon/prscr-category/소셜_에세이-icon.svg
  public/icon/prscr-category/수학_과학_공학-icon.svg
  public/icon/prscr-category/역사-icon.svg
  public/icon/prscr-category/자녀_양육-icon.svg
  public/icon/prscr-category/철학-icon.svg
  public/icon/prscr-category/취미-icon.svg
  public/icon/prscr-category/취업-icon.svg
  src/App.css
  src/App.js
  src/components/HashTag.js
  src/components/Modal/SearchBook.jsx
  src/components/Prescription/OneLinePrscrCard.jsx
  src/components/Prescription/ProcessTitle.jsx
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/pages/Worry/WorryDetail.jsx
  src/styles/Button.module.css
  src/styles/Counseling/ProcessTitle.css
  src/styles/HashTag.css
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Prescription/OneLinePrscrCard.css
  src/styles/Prescription/WidePrescriptionCard.css
  src/styles/SearchBookModal.css
  src/util/index.js
  src/util/toYYYYMMDD.js
Labels: :rocket: Deploy

#200 ✨ Feat: 처방전 API POST,PUT,DELETE 적용
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/pages/PrescriptionWriteStep2.jsx
  src/pages/Worry/WorryDetail.jsx
  src/styles/Counseling/PrescriptionWrite.css
  src/styles/Prescription/WidePrescriptionCard.css
Labels: :sparkles: Feat

#205 ✨ Feat: 한 줄 처방 작성 POST API 로직 구현
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/styles/Prescription/OneLinePrscrWrite.css
Labels: :art: Design, :sparkles: Feat

#206 ✨ Feat: 닉네임, 비밀번호, 자기소개, 직업 정보 수정 API 연결
  src/App.js
  src/components/Login/FormInput .jsx
  src/pages/UserInfo.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/Mypage.jsx
  src/pages/profile/UserInfo.jsx
  src/styles/Login/FormInput.module.css
  src/styles/Profile/Edit.css
  src/styles/Profile/MyPage.css
  src/styles/Profile/UserInfo.css
Labels: :sparkles: Feat

#207 ✨ Feat: 한 줄 처방 목록 페이지 UI 수정 및 API 연결
  public/icon/prscr-category/소설_에세이-icon.svg
  src/components/Prescription/OneLinePrscrCard.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Prescription/OneLinePrscrCard.css
Labels: :art: Design, :sparkles: Feat

#208 ✨ Feat: 한 줄 처방 작성 기능 구현
  package.json
  src/components/DropDown.js
  src/pages/BookDetail.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/profile/Edit.jsx
  src/styles/DropDown.css
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Prescription/OneLinePrscrWrite.css
  yarn.lock
Labels: :sparkles: Feat, :lipstick: Style

#220 ✨ Feat: 한 줄 처방전 상세보기 페이지 구현
  src/App.js
  src/components/Prescription/OneLinePrscrCard.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/styles/HashTag.css
  src/styles/Prescription/OneLinePrscrDetail.css
Labels: :bug: bug, :art: Design, :sparkles: Feat, :lipstick: Style

#221 ✨ Feat: 처방전 작성하기 기능 구현
  src/components/Prescription/ProcessTitle.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/pages/Worry/WorryDetail.jsx
  src/styles/Counseling/CounselingView.css
  src/styles/Counseling/WorryDetail.css
  src/styles/Prescription/WidePrescriptionCard.css
  src/styles/SearchBookModal.css
Labels: :art: Design, :sparkles: Feat, :lipstick: Style

#224 🐛 Fix: 고민 상담 페이지 에러 수정
  src/pages/Prescription/Counseling.jsx
  src/styles/Counseling/Counseling.css
Labels: :bug: bug, :recycle: Refactor

#225 🚀 Deploy: 5월 3주차 릴리즈 배포
  package.json
  public/icon/prscr-category/소설_에세이-icon.svg
  public/index.html
  src/App.css
  src/App.js
  src/components/BookDetailCard.jsx
  src/components/DropDown.js
  src/components/Header.js
  src/components/Login/FormInput .jsx
  src/components/Modal/BaseModal.jsx
  src/components/Modal/ConfirmModal.jsx
  src/components/Modal/LoginErrorModal.jsx
  src/components/Modal/Modal.styled.js
  src/components/Modal/MyListModal.jsx
  src/components/Prescription/OneLinePrscrCard.jsx
  src/components/Prescription/ProcessTitle.jsx
  src/components/Search/SearchBox.jsx
  src/components/Skeleton.jsx
  src/components/interestGrid.jsx
  src/hooks/useLoginForm.js
  src/pages/BookDetail.jsx
  src/pages/Login/Login.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/pages/UserInfo.jsx
  src/pages/Worry/LoadingPage.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/Worry/WorryWrite.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/Mypage.jsx
  src/pages/profile/UserInfo.jsx
  src/styles/Counseling/Counseling.css
  src/styles/Counseling/CounselingView.css
  src/styles/Counseling/PrescriptionWriteStep2.css
  src/styles/Counseling/WorryDetail.css
  src/styles/DropDown.css
  src/styles/HashTag.css
  src/styles/Login/FormInput.module.css
  src/styles/MyListModal.css
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Prescription/OneLinePrscrCard.css
  src/styles/Prescription/OneLinePrscrDetail.css
  src/styles/Prescription/OneLinePrscrWrite.css
  src/styles/Prescription/PrescriptionDetail.css
  src/styles/Prescription/WidePrescriptionCard.css
  src/styles/Profile/Edit.css
  src/styles/Profile/MyPage.css
  src/styles/Profile/UserInfo.css
  src/styles/SearchBookModal.css
  src/styles/Skeleton.css
  yarn.lock
Labels: :rocket: Deploy

#229 ✨ Feat: 한 줄 처방 페이지 기능 구현
  src/App.js
  src/components/DropDown.js
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/OneLinePrscrEdit.jsx
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Prescription/OneLinePrscrDetail.css
  src/styles/Prescription/OneLinePrscrEdit.css
Labels: :bug: bug, :art: Design, :sparkles: Feat, :lipstick: Style

#238 🐛 Fix: 5월 3주차 릴리즈 에러 수정 - 2
  src/pages/Prescription/Counseling.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Counseling/Counseling.css
  src/styles/Profile/MyPage.css
Labels: :bug: bug

#240 ✨ Feat: 내가 작성한 고민 페이지 생성
  src/App.js
  src/pages/profile/MyWorryPage.jsx
  src/styles/Counseling/MyWorryPage.css
Labels: :art: Design, :sparkles: Feat, :lipstick: Style

#242 🎨 Style: 메인 페이지 UI 변경 적용
  src/App.js
  src/assets/images/banner/login-home-banner-1.png
  src/assets/images/banner/login-home-banner-2.png
  src/components/BannerSlider.jsx
  src/components/Card/TodayPrescriptionCard.jsx
  src/components/PrescriptionReviewCard.jsx
  src/pages/LoginHome.jsx
  src/store/nickname-store.js
  src/styles/LoginHome.css
  src/util/toYYYYMMDD.js
Labels: :art: Design, :sparkles: Feat

#246 ✨ Feat: 본인 글인 경우에만 수정, 삭제 버튼 보이기
  src/pages/Prescription/OneLinePrscrDetail.jsx
Labels: :sparkles: Feat

#247 ✨ Feat: 상세고민 페이지에서 본인 고민 글인 경우에만 수정, 삭제 버튼 활성화
  src/pages/Worry/WorryDetail.jsx
Labels: :sparkles: Feat

#253 🎨 Style: 메인페이지 UI 화면 비율 80%, 1080px로 적용
  src/components/BannerSlider.jsx
  src/components/Slider.jsx
  src/pages/LoginHome.jsx
  src/styles/LoginHome.css
  src/styles/Slider.css
Labels: :art: Design

#254 ✨ Feat: 마이페이지 내가 남긴 고민 글 조회 페이지 구현
  src/App.js
  src/pages/profile/Mypage.jsx
Labels: :sparkles: Feat
