Repository kw-bookmedicine/frontend, pull requests merged in 2024-06, with the labels that each got.

#258 🎨 Design: 랜딩 페이지 UI 구현
  public/icon/home/ai-prscr-icon.svg
  public/icon/home/ai_prscr_book.jpeg
  public/icon/home/landing_ai_prscr_icon.svg
  public/icon/home/landing_intro_female_icon_1.png
  public/icon/home/landing_intro_female_icon_2.png
  public/icon/home/landing_intro_male_icon.png
  public/icon/home/landing_join_icon.svg
  public/icon/home/landing_logo_icon.svg
  public/icon/home/landing_top_icon.svg
  public/icon/home/other-prscr-icon.svg
  public/icon/home/other_prscr_book.jpeg
  public/icon/home/other_prscr_user.png
  public/icon/home/prscr_back_book.jpeg
  public/icon/home/prscr_front_book.jpeg
  public/icon/home/prscr_mid_book.jpeg
  public/icon/home/today-prscr-icon.svg
  public/icon/pharmacy_icon.png
  public/icon/pharmacy_icon.svg
  src/App.css
  src/App.js
  src/components/Footer.js
  src/components/Prescription/OneLinePrscrCard.jsx
  src/components/Prescription/PrescriptionCard.jsx
  src/pages/MainHome.jsx
  src/styles/Counseling/PrescriptionCard.css
  src/styles/Footer.module.css
  src/styles/LandingPage.css
  src/styles/Prescription/OneLinePrscrCard.css
Labels: :art: Design, :sparkles: Feat, :lipstick: Style, :dizzy: Animation, ➕Add

#259 🚀 Deploy: 5월 마지막주 릴리즈 배포
  public/icon/home/ai-prscr-icon.svg
  public/icon/home/ai_prscr_book.jpeg
  public/icon/home/landing_ai_prscr_icon.svg
  public/icon/home/landing_intro_female_icon_1.png
  public/icon/home/landing_intro_female_icon_2.png
  public/icon/home/landing_intro_male_icon.png
  public/icon/home/landing_join_icon.svg
  public/icon/home/landing_logo_icon.svg
  public/icon/home/landing_top_icon.svg
  public/icon/home/other-prscr-icon.svg
  public/icon/home/other_prscr_book.jpeg
  public/icon/home/other_prscr_user.png
  public/icon/home/prscr_back_book.jpeg
  public/icon/home/prscr_front_book.jpeg
  public/icon/home/prscr_mid_book.jpeg
  public/icon/home/today-prscr-icon.svg
  public/icon/oneLine-prscr/after-help.svg
  public/icon/oneLine-prscr/after-like.svg
  public/icon/oneLine-prscr/before-help.svg
  public/icon/oneLine-prscr/before-like.svg
  public/icon/pharmacy_icon.png
  public/icon/pharmacy_icon.svg
  src/App.css
  src/App.js
  src/components/BannerSlider.jsx
  src/components/Footer.js
  src/components/Prescription/OneLinePrscrCard.jsx
  src/components/Prescription/PrescriptionCard.jsx
  src/components/Slider.jsx
  src/pages/LoginHome.jsx
  src/pages/MainHome.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Counseling/PrescriptionCard.css
  src/styles/Footer.module.css
  src/styles/LandingPage.css
  src/styles/LoginHome.css
  src/styles/Prescription/OneLinePrscrCard.css
  src/styles/Prescription/OneLinePrscrDetail.css
  src/styles/Prescription/WidePrescriptionCard.css
  src/styles/Profile/MyOneLinePrescription.css
  src/styles/Profile/MyPrescription.css
  src/styles/Slider.css
Labels: :rocket: Deploy

#262 🐛 Fix: 5월 마지막주 릴리즈 에러 수정
  src/App.js
  src/components/Button.jsx
  src/components/Header.js
  src/pages/SmallCategory.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Prescription/OneLinePrescription.css
  src/styles/Profile/MyOneLinePrescription.css
  src/styles/Profile/MyPage.css
  src/styles/Profile/MyPrescription.css
Labels: :bug: bug

#268 :memo: Docs: 회원가입 요청 필드값 변경 적용
  src/pages/Login/Signup3.jsx
  src/store/signup-store.js
Labels: :memo: Docs

#270 Fix: birthDate -> birth 필드값 수정
  src/pages/Login/Signup2.jsx
  src/pages/Login/Signup2Oauth.jsx
Labels: :memo: Docs

#271 ✨ Feat: 복용내역 페이지네이션 적용 및 로딩 스피너 컴포넌트 추가
  src/components/Loading/LoadingSpinner.jsx
  src/components/Modal/MyListModal.jsx
  src/styles/Loading/LoadingSpinner.css
  src/styles/MyListModal.css
  src/styles/PickBookItem.css
Labels: :sparkles: Feat, :dizzy: Animation

#273 :sparkles: Feat: 복용내역 조회 및 요청 API 연결
  src/components/Modal/MyListModal.jsx
Labels: :sparkles: Feat

#274 Fix: 이름 입력창 제거
  src/pages/Login/Signup2Oauth.jsx
Labels: :art: Design, :memo: Docs

#277 🎨 Design: AI 처방전이 없을 경우 보일 이미지와 문구 디자인
  public/images/worry_detail/no_prscr_img.png
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Worry/WorryDetail.jsx
  src/styles/Counseling/WorryDetail.css
  src/styles/Prescription/OneLinePrescription.css
Labels: :art: Design

#279 🎨 Design: 한 줄 처방이 있을 때, 없을 때 UI 구현 및 API 연결
  public/images/book-detail/write_prscr_img.png
  src/components/Prescription/OneLinePrscrCard.jsx
  src/pages/BookDetail.jsx
  src/styles/BookDetail.css
  src/styles/Prescription/OneLinePrscrCard.css
Labels: :bug: bug, :art: Design

#281 Fix: 소셜로그인 새창 띄우기에서 현재 창 페이지 이동으로 수정
  src/pages/Login/Login.jsx
Labels: :bug: bug, :memo: Docs

#282 ✨ Feat: 한 줄 처방 상세페이지 공감 기능 구현
  src/components/Prescription/OneLinePrscrCard.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/styles/Prescription/OneLinePrscrDetail.css
Labels: :art: Design, :sparkles: Feat

#283 🎨 Design: 푸터 수정
  src/pages/Search/Search.jsx
  src/styles/Profile/Edit.css
Labels: :art: Design, :lipstick: Style

#285 ✨ Feat: 페이지별 로딩스피너 적용
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/SmallCategory.jsx
  src/styles/SmallCategory.css
Labels: :sparkles: Feat

#289 🐛 Fix: 도움이 되었어요 에러 해결
  src/components/Prescription/OneLinePrscrCard.jsx
Labels: :bug: bug

#291 📝 Docs: 키워드 검색 대분류 제거 및 검색 타입 보이도록 수정
  src/pages/Search/SearchResult.jsx
Labels: :memo: Docs

#292 🐛 Fix: 6월 1주 릴리즈 에러 수정
  src/pages/Login/Login.jsx
  src/pages/LoginHome.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/pages/profile/Mypage.jsx
  src/pages/profile/UserInfo.jsx
  src/styles/LoginHome.css
Labels: :bug: bug, :sparkles: Feat, :memo: Docs, :lipstick: Style, :recycle: Refactor

#293 🐛 Fix: 회원가입 후 에러 수정
  src/pages/Login/Signup3.jsx
  src/styles/BookDetail.css
Labels: :bug: bug

#294 🐛 Fix: 자영업으로 되어 있어서 에러 나던 문제 자영업자로 변경
  src/components/DropDown.js
  src/pages/Login/Signup2.jsx
  src/pages/Login/Signup2Oauth.jsx
Labels: :bug: bug

#295 🐛 Fix: 6월 1주 릴리즈 에러 수정
  src/assets/icons/chevron_up.svg
  src/components/DropDown.js
  src/components/Loading/LoadingSpinner.jsx
  src/components/Prescription/OneLinePrscrCard.jsx
  src/components/ScrollToTop.jsx
  src/pages/BookDetail.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Signup2.jsx
  src/pages/Login/Signup2Oauth.jsx
  src/pages/Login/Signup3.jsx
  src/pages/LoginHome.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/pages/profile/Mypage.jsx
  src/pages/profile/UserInfo.jsx
  src/styles/BookDetail.css
  src/styles/LoginHome.css
  src/styles/ScrollToTop.css
Labels: :bug: bug, :rocket: Deploy

#296 ✨ Feat: 고민 글에 대한 AI 처방전 구현
  public/images/book-detail/write_prscr_img_2.png
  public/images/worry_detail/no_prscr_img.png
  src/components/ArrowTitle.js
  src/components/Prescription/AiPrscrCard.jsx
  src/pages/BookDetail.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Worry/WorryDetail.jsx
  src/styles/BookDetail.css
  src/styles/Counseling/WorryDetail.css
  src/styles/Prescription/AiPrscrCard.css
Labels: :art: Design, :sparkles: Feat

#297 🐛 Fix: 6월 1주차 릴리즈 에러 수정 - (2)
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/MyPrescription.jsx
  src/styles/Counseling/WorryDetail.css
  src/styles/DropDown.css
  src/styles/Prescription/WidePrescriptionCard.css
Labels: :bug: bug, :sparkles: Feat, :lipstick: Style

#298 🚀 Deploy: 6월 1주 릴리즈2 배포
  public/images/book-detail/write_prscr_img_2.png
  public/images/worry_detail/no_prscr_img.png
  src/components/ArrowTitle.js
  src/components/Prescription/AiPrscrCard.jsx
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/BookDetail.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/MyPrescription.jsx
  src/styles/BookDetail.css
  src/styles/Counseling/WorryDetail.css
  src/styles/DropDown.css
  src/styles/Prescription/AiPrscrCard.css
  src/styles/Prescription/WidePrescriptionCard.css
Labels: :rocket: Deploy

#300 🐛 Fix: 로고 클릭 시 메인 화면으로 이동할 수 있도록 수정
  src/components/Header.js
Labels: :bug: bug

#301 🚀 Deploy: 로고 클릭 시 메인 화면으로 이동할 수 있도록 수정 후 재배포
  src/components/Header.js
Labels: :rocket: Deploy

#302 🐛 Fix: 6월 1주 릴리즈 2 에러 수정
  src/pages/BookDetail.jsx
  src/pages/BookList.jsx
  src/pages/LoginHome.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/OneLinePrscrEdit.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/SmallCategory.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/pages/profile/Mypage.jsx
  src/pages/profile/UserInfo.jsx
  src/styles/Profile/Edit.css
Labels: :bug: bug, :memo: Docs

#303 🚀 Deploy: 6월 1주 릴리즈2 에러 수정사항 추가 배포
  src/pages/BookDetail.jsx
  src/pages/BookList.jsx
  src/pages/LoginHome.jsx
  src/pages/Prescription/Counseling.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/OneLinePrscrEdit.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/SmallCategory.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/pages/profile/Mypage.jsx
  src/pages/profile/UserInfo.jsx
  src/styles/Profile/Edit.css
Labels: :rocket: Deploy

#309 :sparkles: Feat: 메일 페이지 오늘의 처방전, 베스트 셀러, 신간, 나와 비슷한 사람들 책 API 연결
  src/components/Slider.jsx
  src/pages/LoginHome.jsx
  src/styles/Slider.css
Labels: :sparkles: Feat

#322 🐛 Fix: 6월 1주 릴리즈2 에러 수정
  src/pages/BookDetail.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Counseling/WorryDetail.css
  src/styles/Profile/Edit.css
Labels: :bug: bug, :sparkles: Feat, :lipstick: Style

#323 🚀 Deploy: 6월 1주 릴리즈2 에러 수정 후 재배포
  src/pages/BookDetail.jsx
  src/pages/Prescription/OneLinePrescription.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Counseling/WorryDetail.css
  src/styles/Profile/Edit.css
Labels: :rocket: Deploy

#326 ✨ Feat: 메인 페이지 추천 책 클릭 시, 책 상세페이지 이동 및 값이 없을 시, alert 처리
  src/components/Card/TodayPrescriptionCard.jsx
  src/components/PrescriptionReviewCard.jsx
  src/components/Slider.jsx
  src/pages/LoginHome.jsx
  src/styles/Slider.css
Labels: :art: Design, :sparkles: Feat, :recycle: Refactor, :rocket: Deploy

#329 📝 Docs: 추가 기능 구현
  public/index.html
  src/components/Card/TodayPrescriptionCard.jsx
  src/components/Loading/LoadingSpinner.jsx
  src/components/PrescriptionReviewCard.jsx
  src/components/Search/SearchBox.jsx
  src/components/SearchResultListModal.jsx
  src/components/Slider.jsx
  src/pages/BookDetail.jsx
  src/pages/LoginHome.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/Worry/WorryWrite.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Counseling/MyWorryPage.css
  src/styles/Profile/Edit.css
  src/styles/Profile/MyOneLinePrescription.css
  src/styles/Slider.css
Labels: :bug: bug, :art: Design, :memo: Docs, :lipstick: Style

#330 🚀 Deploy: 유저 테스트 전 최종 배포
  public/index.html
  src/components/Search/SearchBox.jsx
  src/pages/BookDetail.jsx
  src/pages/LoginHome.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/Edit.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/pages/profile/Mypage.jsx
  src/styles/Counseling/MyWorryPage.css
  src/styles/Profile/Edit.css
  src/styles/Profile/MyOneLinePrescription.css
Labels: :rocket: Deploy

#333 Fix: 한 줄 처방 작성, 처방전 작성 검색창 target=modal로 수정
  src/pages/Prescription/OneLinePrscrWrite.jsx
  src/pages/Prescription/PrescriptionWrite.jsx
Labels: :memo: Docs

#335 Fix: 한 줄 처방 삭제 .then 버그 수정
  src/pages/Prescription/OneLinePrscrDetail.jsx
Labels: :bug: bug

#337 Fix: 한줄 처방 수정시 페이지 이동하도록 수정
  src/pages/Prescription/OneLinePrscrEdit.jsx
  src/pages/Prescription/OneLinePrscrWrite.jsx
Labels: :memo: Docs

#339 ✨ Feat: 6월 1주 릴리즈2 추가 구현 사항
  src/pages/BookDetail.jsx
  src/pages/LoginHome.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/styles/BookDetail.css
Labels: :bug: bug, :art: Design, :sparkles: Feat, :lipstick: Style

#340 🚀 Deploy: 6월 2주 릴리즈 배포
  src/pages/BookDetail.jsx
  src/pages/LoginHome.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/profile/MyOneLinePrescription.jsx
  src/pages/profile/MyPrescription.jsx
  src/pages/profile/MyWorryPage.jsx
  src/styles/BookDetail.css
Labels: :rocket: Deploy

#342 🐛 Fix: 처방전 상세보기 페이지 타이틀 UI 수정
  src/components/Prescription/ProcessTitle.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
Labels: :bug: bug

#343 🐛 Fix: 처방전 상세보기 페이지 에러 수정 후 재배포
  src/components/Prescription/ProcessTitle.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
Labels: :bug: bug, :rocket: Deploy

#344 🐛 Fix: 6월 2주 릴리즈 에러 수정
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/profile/MyPrescription.jsx
Labels: :bug: bug, :memo: Docs

#345 🐛 Fix: 6월 2주 릴리즈 2차 에러 수정 후 재배포
  src/components/Prescription/WidePrescriptionCard.jsx
  src/pages/Prescription/PrescriptionDetail.jsx
  src/pages/profile/MyPrescription.jsx
Labels: :rocket: Deploy

#347 :bug: Fix: 소설/에세이 오타로 ETC 요청 버그 수정
  src/pages/Worry/WorryWrite.jsx
Labels: :bug: bug, :memo: Docs

#349 ✨ Feat: 리액트 쿼리로 닉네임 정보 조회 변경
  package-lock.json
  package.json
  src/components/Button.jsx
  src/components/PickBookList.jsx
  src/hooks/useNickname.js
  src/index.js
  src/pages/LoginHome.jsx
  src/pages/Prescription/OneLinePrscrDetail.jsx
  src/pages/Worry/WorryDetail.jsx
  src/pages/Worry/WorryWrite.jsx
  src/queries/queryKeys.js
  src/services/api.js
  src/store/nickname-store.js
  src/styles/Counseling/WorryDetail.css
  src/util/TanstackProviders.jsx
  yarn.lock
Labels: :sparkles: Feat, :recycle: Refactor
