Repository kw-bookmedicine/frontend, pull requests merged in 2024-03, with the labels that each got.

#60 📝 Docs: 대분류 선택 시 선택 요소 포커스 기능 테스트
  src/pages/Signup3.jsx
  src/styles/Signup3.css
Labels: :memo: Docs

#63 ✨ Feat: access, refresh token으로 /category/big API 요청 구현
  src/pages/Login.jsx
  src/pages/Search.jsx
Labels: :sparkles: Feat

#78 ✨ Feat: 대분류에 따른 책 리스트 데이터바인딩 처리
  src/components/BookCard.js
  src/components/BookListSlide.js
  src/pages/BookList.jsx
  src/styles/BookCard.module.css
  src/styles/BookList.css
  src/styles/BookListSlide.module.css
Labels: :art: Design, :sparkles: Feat, :memo: Docs

#84 ✨ Feat: 책 상세보기 페이지 데이터 바인딩
  src/App.js
  src/components/BookDetailCard.jsx
  src/pages/BookDetail.jsx
  src/pages/SmallCategory.jsx
Labels: :sparkles: Feat

#87 ♻️ Refactor: 중분류, 소분류, 책 상세페이지 리팩토링
  src/components/BookCard.js
  src/components/BookDetailCard.jsx
  src/components/BookListSlide.js
  src/pages/BookDetail.jsx
  src/pages/SmallCategory.jsx
  src/styles/ArrowTitle.module.css
  src/styles/BookCard.module.css
Labels: :recycle: Refactor

#89 🎨 Design: 경험 추가하기 모달창 디자인
  src/components/BookDetailCard.jsx
  src/components/Button.jsx
  src/components/Modal/Experience.jsx
  src/pages/BookDetail.jsx
  src/styles/BookDetailCard.css
  src/styles/Experience.css
Labels: :art: Design

#93 ✨ Feat: 무한스크롤 구현
  src/components/FeedCard.js
  src/pages/Feed.jsx
  src/styles/Feed.css
  src/styles/FeedCard.css
Labels: :sparkles: Feat

#94 ✨ Feat: /api/feeds/all api 연결
  src/components/FeedCard.js
  src/pages/Feed.jsx
  src/styles/Feed.css
  src/styles/FeedCard.css
Labels: :sparkles: Feat

#97 🎨 Design: 고민 상담 페이지 UI 1차 구현
  .env
  src/App.js
  src/components/Header.js
  src/components/Prescription/CounselingView.jsx
  src/pages/Counseling.jsx
  src/styles/Counseling.css
  src/styles/Counseling/CounselingView.css
Labels: :art: Design

#101 🎨 Design: 증상 상세보기 페이지 와이어프레임 구현
  src/App.js
  src/components/Prescription/CounselingView.jsx
  src/components/Prescription/ProcessTitle.jsx
  src/pages/Counseling.jsx
  src/pages/WorryDetail.jsx
  src/styles/Counseling/Counseling.css
  src/styles/Counseling/ProcessTitle.css
  src/styles/Counseling/WorryDetail.css
Labels: :art: Design, :sparkles: Feat

#105 :memo: Docs: 책 클릭 시, 라우팅 연결 수정
  src/components/SearchResultListModal.jsx
  src/pages/SearchResult.jsx
Labels: :memo: Docs

#106 🎨 Design: 처방전 등록 및 처방 사유 페이지 1차 디자인, 기능 구현
  public/icon/search_icon.png
  public/icon/search_icon_light.png
  src/App.js
  src/assets/loading_thumbnail_x4.png
  src/components/Modal/SearchBook.jsx
  src/components/Prescription/ProcessTitle.jsx
  src/pages/PrescriptionWrite.jsx
  src/pages/PrescriptionWriteStep2.jsx
  src/pages/WorryDetail.jsx
  src/services/api.js
  src/styles/Counseling/PrescriptionWrite.css
  src/styles/Counseling/PrescriptionWriteStep2.css
  src/styles/Counseling/ProcessTitle.css
  src/styles/Counseling/WorryDetail.css
  src/styles/SearchBookModal.css
Labels: :art: Design, :sparkles: Feat, :memo: Docs, :lipstick: Style

#107 💄 Style: 고민상담 페이지 UI 2차 구현
  public/icon/art_icon.png
  public/icon/general_icon.png
  public/icon/history_icon.png
  public/icon/language_icon.png
  public/icon/literature_icon.png
  public/icon/philosophy_icon.png
  public/icon/religion_icon.png
  public/icon/science_icon.png
  public/icon/social_icon.png
  public/icon/tech_icon.png
  src/pages/Counseling.jsx
  src/styles/Counseling/Counseling.css
  src/styles/Counseling/CounselingView.css
Labels: :lipstick: Style

#108 🎨 Design: 고민 상세보기 페이지 디자인 구현
  public/icon/pharmacy_icon.png
  public/icon/pharmacy_icon_2.png
  public/loading_thumbnail_x4.png
  src/components/Prescription/PrescriptionCard.jsx
  src/pages/WorryDetail.jsx
  src/styles/Counseling/PrescriptionCard.css
  src/styles/Counseling/WorryDetail.css
  src/styles/GlobalStyles.js
Labels: :art: Design, :memo: Docs, :lipstick: Style
