Repository kw-bookmedicine/frontend, pull requests merged in 2024-01, with the labels that each got.

#17 Feature/home
  .gitmessage.txt
  src/styles/HomeStyles.css
Labels: :art: Design, :sparkles: Feat

#18 :bug: Login 페이지 아이콘 깨짐 수정 및 input 폼 버그 수정
  src/App.js
  src/pages/Login.jsx
  src/styles/Join2.style.js
  yarn.lock
Labels: :bug: bug

#19 :memo: Docs: react-hook-form 설치 및 입력 삭제 버튼 위치 수정, 이메일 직접 입력 및 선택 적용
  package.json
  src/pages/Join2.jsx
  yarn.lock
Labels: :memo: Docs

#20 Feature/login home
  package.json
  src/assets/main-banner.png
  src/components/PrescriptionReviewCard.jsx
  src/components/Slider.jsx
  src/index.js
  src/pages/Join2.jsx
  src/pages/LoginHome.jsx
  src/styles/LoginHome.css
  src/styles/SearchStyles.css
  src/styles/Slider.css
  yarn.lock
Labels: :art: Design

#21 :art: Design: 책 상세보기 페이지 디자인 추가 #13
  public/icon/title_rightArrow.png
  src/App.js
  src/components/ArrowTitle.js
  src/components/BookCard.js
  src/components/Button.js
  src/components/Footer.js
  src/components/HashTag.js
  src/components/Review.js
  src/pages/BookDetail.jsx
  src/styles/ArrowTitle.module.css
  src/styles/BookCard.module.css
  src/styles/BookDetail.css
  src/styles/Button.module.css
  src/styles/Footer.module.css
  src/styles/HashTag.css
  src/styles/Review.css
Labels: :art: Design, :sparkles: Feat

#23 :lipstick: Style: 책 상세정보 페이지 높이 수정
  src/styles/BookDetail.css
Labels: :art: Design

#27 ✨ Feat: 대분류 api GET 요청 연결 로직 구현
  package.json
  src/App.js
  src/pages/BookList.jsx
  src/pages/Search.jsx
  yarn.lock
Labels: :sparkles: Feat

#32 :lipstick: Design: 검색 페이지 UI 디자인 구현
  src/assets/category-book-img1.png
  src/assets/category-book-img2.png
  src/assets/category-book-img3.png
  src/assets/category-book-img4.png
  src/assets/category-book-img5.png
  src/assets/category-book-img6.png
  src/assets/category-book-img7.png
  src/assets/category-book-img8.png
  src/assets/search-book-Harry_Potter.jpg
  src/pages/Search.jsx
  src/styles/JoinStyles.css
  src/styles/SearchStyles.css
Labels: :art: Design
