Repository kw-bookmedicine/frontend, pull requests merged in 2024-02, with the labels that each got.

#43 ✨ Feat: 마이페이지 정보 수정 기능 구현
  src/components/DropDown.js
  src/hooks/useDetectClose.js
  src/pages/Edit.jsx
  src/pages/Mypage.jsx
  src/pages/UserInfo.jsx
  src/styles/DropDown.css
  src/styles/MyPage.css
  src/styles/UserInfo.css
Labels: :art: Design, :sparkles: Feat, :memo: Docs

#45 :sparkles: Feat: 검색 페이지, 카테고리 대·중분류 API 연결
  src/assets/category-book-img2.png
  src/assets/category-book-img3.png
  src/assets/category-book-img4.png
  src/assets/category-book-img5.png
  src/assets/category-book-img6.png
  src/assets/category-book-img7.png
  src/assets/category-book-img8.png
  src/assets/category-book-기술과학.jpg
  src/assets/category-book-문학.png
  src/assets/category-book-사회과학.jpg
  src/assets/category-book-언어.jpg
  src/assets/category-book-역사.jpg
  src/assets/category-book-예술.jpg
  src/assets/category-book-자연과학.jpg
  src/assets/category-book-종교.jpg
  src/assets/category-book-철학.jpg
  src/assets/category-book-총류.jpg
  src/components/Modal.jsx
  src/components/SearchResultList.jsx
  src/pages/Abc.jsx
  src/pages/BookList.jsx
  src/pages/Login.jsx
  src/pages/LoginHome.jsx
  src/pages/Search.jsx
  src/styles/SearchResultList.css
  src/styles/SearchStyles.css
Labels: :sparkles: Feat, :memo: Docs

#46 Feature/profile
  public/index.html
  src/App.css
  src/components/Button.js
  src/components/DropDown.js
  src/components/Modal/MyListModal.jsx
  src/components/Modal/Portal.jsx
  src/components/Modal2.js
  src/components/PickBookList.js
  src/components/SearchResultList.jsx
  src/font/Recipekorea 레코체 FONT.ttf
  src/pages/Mypage.jsx
  src/pages/UserInfo.jsx
  src/styles/Button.module.css
  src/styles/GlobalStyles.js
  src/styles/Modal2.css
  src/styles/MyBookList.css
  src/styles/MyListModal.css
  src/styles/PickBookList.css
  src/styles/SearchResultList.css
Labels: :art: Design, :sparkles: Feat, :memo: Docs

#52 ♻️ Refactor: 로그인 및 회원가입, 아이디, 비밀번호 찾기 페이지 수정
  src/App.js
  src/assets/Login-Banner.png
  src/components/Button.jsx
  src/components/LoginLayout.js
  src/components/Signup/FindID.jsx
  src/components/Signup/FindPW.jsx
  src/pages/FindUserInfo.jsx
  src/pages/Join.jsx
  src/pages/Join2.jsx
  src/pages/Login.jsx
  src/pages/LoginFind.jsx
  src/pages/Signup2.jsx
  src/pages/Signup3.jsx
  src/styles/Button.module.css
  src/styles/JoinStyles.css
  src/styles/Signup2.css
  src/styles/Signup3.css
Labels: :bug: bug, :sparkles: Feat, :memo: Docs

#57 🎨 Design: 관심사 선택 디자인 구현
  src/assets/interest_category_art.png
  src/assets/interest_category_general.png
  src/assets/interest_category_history.png
  src/assets/interest_category_language.png
  src/assets/interest_category_literature.png
  src/assets/interest_category_natural-science.png
  src/assets/interest_category_philosophy.png
  src/assets/interest_category_religion.png
  src/assets/interest_category_social-science.png
  src/assets/interest_category_tech.png
  src/pages/Signup3.jsx
  src/styles/Signup3.css
Labels: :art: Design
